name: MinecraftCore
version: "1.0"
api: ["1.0.0"]
author: jarofbilly
description: A basic plugin for NukkitX
main: billyjar.MinecraftCore.main

commands:
  example:
    description: Example command
    usage: "/example"
    aliases: []
    permission: MinecraftCore.command.compass
    permission-message: "You do not have the required permission to run /example"
  addperm:
    description: New Example command
    usage: "/example"
    aliases: []